manifest_version = 0

[dependencies]
glm = "gh:g-truc/glm#1.0.1"
spdlog = "gh:gabime/spdlog@^1.14.0"
stb = "gh:nothings/stb"
json = "gh:nlohmann/json@^3.11.0"
openal-soft = "gh:kcat/openal-soft#1.23.1"
freetype = "gl:freetype/freetype#VER-2-13-2"
msdf-atlas-gen = "gh:Chlumsky/msdf-atlas-gen@1.3"
imgui = "gh:ocornut/imgui/docking"

[dependencies.tinygltf]
type = "github"
username = "syoyo"
repository = "tinygltf"
version = "^2.9.0"

[dev-dependencies]
catch2 = "gh:catchorg/catch2@3.6.0"

[desktop-dependencies]
glfw = "gh:glfw/glfw#3.4"